#!/bin/bash
sshpass -p "M2Robots" scp donkeycar/parts/*.py pi@192.168.31.114:/home/pi/code/selfdrive/pq/donkeycar/donkeycar/parts/
sshpass -p "M2Robots" scp donkeycar/templates/*.py pi@192.168.31.114:/home/pi/code/selfdrive/pq/donkeycar/donkeycar/templates/

#sshpass -p "M2Robots" scp /home/dev/code/paperplaneM2R/programmingSDK/pySDK/src/m2controller/*.py pi@192.168.31.114:/home/pi/env/lib/python3.7/site-packages/m2controller/


